### ISSUE TITLE
Octal check fails on newer kernels

### ISSUE THREAD

**Issue by ArkadiuszRaj** [ni/usb3vision#3]
in v3v_core.c:138 following code is not compiling well:

```static DEVICE_ATTR(name, S_IWUGO | S_IRUGO, name##_show, name##_store);```

Temporary solution is changing this line to :  

```static DEVICE_ATTR(name, 0660, name##_show, name##_store);```

**Comment by katieensign** [comment]
Thanks for the feedback here about compatibility with modern kernels. My changes in release 1.3.0 (see release notes for more details) should allow users to compile in kernel versions up to 4.9. Since this module is out-of-tree (and for my own use-case), my goal is to keep things backwards-compatible if possible, so I addressed them slightly differently (with #ifdefs for kernel version) than the pull request provided by theg4sh but the changes should be functionally equivalent. I had actually already made these changes in parallel, so I just posted in release 1.3.0 the changes I had validated. Since I just saw the pull request a couple days ago, I was not able to incorporate the Makefile changes yet. I think those changes are a helpful improvement, and I would like to incorporate them in a future release. Since the core issue of compilation is now addressed in release 1.3.0, I will close this issue, but again I'd like to still put the Makefile changes in the next release.
